package formatter

import (
	"fmt"
	"strings"

	"github.com/millstonehq/crossplane-plan/pkg/differ"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// GitHubFormatter formats diffs for GitHub PR comments
type GitHubFormatter struct{}

// NewGitHubFormatter creates a new GitHubFormatter
func NewGitHubFormatter() *GitHubFormatter {
	return &GitHubFormatter{}
}

// FormatDiff formats a diff result as a GitHub-flavored markdown comment
func (f *GitHubFormatter) FormatDiff(xr *unstructured.Unstructured, result *differ.DiffResult) string {
	var b strings.Builder

	// Header
	b.WriteString("## 🔄 Crossplane Preview\n\n")
	
	// XR information
	b.WriteString(fmt.Sprintf("**Resource:** `%s/%s`\n", xr.GetKind(), xr.GetName()))
	if xr.GetNamespace() != "" {
		b.WriteString(fmt.Sprintf("**Namespace:** `%s`\n", xr.GetNamespace()))
	}
	b.WriteString("\n")

	// Summary
	if !result.HasChanges {
		b.WriteString("### ✅ No Changes\n\n")
		b.WriteString("This PR will not modify any infrastructure resources.\n\n")
		// Footer
		b.WriteString("---\n")
		b.WriteString("_Generated by [crossplane-plan](https://github.com/millstonehq/crossplane-plan)_\n")
		return b.String()
	}

	// Changes detected
	b.WriteString("### 📋 Changes Detected\n\n")
	b.WriteString(result.Summary)
	b.WriteString("\n\n")

	// Diff output
	b.WriteString("<details>\n")
	b.WriteString("<summary>📝 View Full Diff</summary>\n\n")
	b.WriteString("```diff\n")
	b.WriteString(result.RawDiff)
	b.WriteString("\n```\n")
	b.WriteString("</details>\n\n")

	// Infrastructure drift detection
	if len(result.ManagedResources) > 0 {
		f.formatInfrastructureDrift(&b, result.ManagedResources)
	}

	// Footer with transparency about stripped fields
	f.formatStrippedFieldsFooter(&b, result.StrippedFields)

	return b.String()
}

// formatInfrastructureDrift formats infrastructure drift detection results
func (f *GitHubFormatter) formatInfrastructureDrift(b *strings.Builder, managedResources []differ.ManagedResourceState) {
	// Check if any resources have drift
	hasDrift := false
	for _, mr := range managedResources {
		if len(mr.DeclaredVsActual) > 0 {
			hasDrift = true
			break
		}
	}

	if !hasDrift {
		return
	}

	b.WriteString("### ☁️ Infrastructure State Analysis\n\n")
	b.WriteString("Comparing your declared configuration against actual infrastructure state:\n\n")

	for _, mr := range managedResources {
		if len(mr.DeclaredVsActual) == 0 {
			continue
		}

		resourceName := mr.Resource.GetKind() + "/" + mr.Resource.GetName()

		// Warning header based on management policy
		if mr.IsReadOnly {
			b.WriteString(fmt.Sprintf("#### ⚠️ `%s` (Read-Only Mode)\n\n", resourceName))
			b.WriteString("**Your declaration doesn't match actual infrastructure:**\n\n")
		} else {
			b.WriteString(fmt.Sprintf("#### → `%s` (Will Modify Infrastructure)\n\n", resourceName))
			b.WriteString("**Infrastructure will be changed to match your declaration:**\n\n")
		}

		// Check if status.atProvider is available
		if !mr.HasAtProvider {
			b.WriteString("⚠️ **Warning:** Infrastructure state unavailable - resource not reconciled or error\n\n")
			if !mr.IsReady {
				b.WriteString("_Resource is not Ready. Check resource status for errors._\n\n")
			}
			continue
		}

		// Show field-by-field comparison
		b.WriteString("| Field | Your Declaration | Actual Infrastructure |\n")
		b.WriteString("|-------|------------------|----------------------|\n")

		for field, comparison := range mr.DeclaredVsActual {
			declaredStr := fmt.Sprintf("`%v`", comparison.Declared)
			actualStr := fmt.Sprintf("`%v`", comparison.Actual)
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", field, declaredStr, actualStr))
		}
		b.WriteString("\n")

		// Show what will happen
		if mr.IsReadOnly {
			b.WriteString("```\n")
			b.WriteString("ℹ️ With managementPolicies: [Observe]:\n")
			b.WriteString("  • Infrastructure will NOT be modified\n")
			b.WriteString("  • This mismatch will persist after merge\n")
			b.WriteString("  \n")
			b.WriteString("  Options:\n")
			b.WriteString("  • Update your declaration to match infrastructure\n")
			b.WriteString("  • Remove Observe mode if you want to apply changes\n")
			b.WriteString("```\n\n")
		} else {
			b.WriteString("```\n")
			b.WriteString("→ Infrastructure WILL be modified to match your spec\n")
			b.WriteString("```\n\n")
		}
	}
}

// FormatMultipleDiffs formats multiple XR diffs into a single comment
func (f *GitHubFormatter) FormatMultipleDiffs(results map[string]*differ.DiffResult) string {
	var b strings.Builder

	// Header
	b.WriteString("## 🔄 Crossplane Preview\n\n")

	// Count total changes
	totalChanges := 0
	totalResources := len(results)
	for _, result := range results {
		if result.HasChanges {
			totalChanges++
		}
	}

	// Summary
	b.WriteString(fmt.Sprintf("**Resources:** %d total, %d with changes\n\n", totalResources, totalChanges))

	if totalChanges == 0 {
		b.WriteString("### ✅ No Changes\n\n")
		b.WriteString("This PR will not modify any infrastructure resources.\n")
		return b.String()
	}

	// List resources with changes
	b.WriteString("### 📋 Resources with Changes\n\n")
	for name, result := range results {
		if result.HasChanges {
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", name, result.Summary))
		}
	}
	b.WriteString("\n")

	// Individual diffs
	for name, result := range results {
		if !result.HasChanges {
			continue
		}

		b.WriteString(fmt.Sprintf("### `%s`\n\n", name))
		b.WriteString("<details>\n")
		b.WriteString("<summary>📝 View Diff</summary>\n\n")
		b.WriteString("```diff\n")
		b.WriteString(result.RawDiff)
		b.WriteString("\n```\n")
		b.WriteString("</details>\n\n")
	}

	// Collect all stripped fields from all results
	var allStrippedFields []differ.StrippedField
	seenFields := make(map[string]bool)
	for _, result := range results {
		for _, field := range result.StrippedFields {
			// Deduplicate by path (same fields stripped across multiple XRs)
			if !seenFields[field.Path] {
				allStrippedFields = append(allStrippedFields, field)
				seenFields[field.Path] = true
			}
		}
	}

	// Footer with transparency about stripped fields
	f.formatStrippedFieldsFooter(&b, allStrippedFields)

	return b.String()
}

// formatStrippedFieldsFooter adds a transparency footer showing stripped fields
func (f *GitHubFormatter) formatStrippedFieldsFooter(b *strings.Builder, strippedFields []differ.StrippedField) {
	b.WriteString("---\n")
	b.WriteString("_Generated by [crossplane-plan](https://github.com/millstonehq/crossplane-plan)_\n")

	// Only show stripped fields section if fields were actually stripped
	if len(strippedFields) == 0 {
		return
	}

	b.WriteString("\n")
	b.WriteString("<details>\n")
	b.WriteString("<summary>ℹ️ Diff excludes deployment-specific overrides</summary>\n\n")
	b.WriteString("The following fields are hidden as they represent temporary PR environment configuration:\n\n")
	b.WriteString("| Field | Reason |\n")
	b.WriteString("|-------|--------|\n")

	for _, field := range strippedFields {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", field.Path, field.Reason))
	}

	b.WriteString("\n")
	b.WriteString("These overrides won't persist when merged to main.\n\n")
	b.WriteString("_To disable field stripping, set `--no-strip-defaults` flag_\n")
	b.WriteString("</details>\n")
}
